### PR TITLE
Add API documentation.

### PR DESCRIPTION
**Pull request by waynemwashuma**
This uses jsdoc package to generate API docs.

To automatically generate docs, use the following npm commands:
```bash
#installs the dependencies.Run only once after cloning.
npm i
```
```bash
#generates the actual docs
npm run docs
```

The docs should be generated once for every version release.

### CODE REVIEW

**Comment by waynemwashuma** [comment]
When running the doc generator,you will realise it throws a lot of nonfatal errors.This is because jsdoc doesnt support Typescript tags and annotations.Just ignore them for now as it doesn't impede doc generation.

@Ian-Cornelius, you should define one entry point for your package as currently,this will not scale with each source folder added unless you add them into the includes of the configuration every time.

**Comment by Ian-Cornelius** [comment]
@waynemwashuma mega job with this one. Thank you.

I'll see what I can do as far as defining a single entry point is concerned, though as far as the framework's architecture is concerned I don't expect massive changes in structure, so just working with the config file will be fine.

Just one more thing, can you add the bin and base-history folder to the config and have their docs generated as well? I think with that we should be good to go.

**Comment by waynemwashuma** [comment]
> Just one more thing, can you add the bin and base-history folder to the config and have their docs generated as well?

Done.

**Comment by Ian-Cornelius** [comment]
Awesome work. Thank you!

I'll see how I can host the files on GitHub for now before the official site goes live. I appreciate the contribution!

**Pull request merged**
